project:
  type: website
  output-dir: _site

website:
  title: "eeg-alpha"
  description: "Open-source alpha neurofeedback training with OpenBCI"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        menu:
          - text: "EEG Basics"
            href: tutorials/00-eeg-basics.qmd
          - text: "Understanding EEG Boards"
            href: tutorials/01-understanding-boards.qmd
          - text: "Hello BrainFlow"
            href: tutorials/02-hello-brainflow.qmd
          - text: "EEG Neurophysiology"
            href: tutorials/05-eeg-neurophysiology.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  warning: false
